version: 2
updates:
  - package-ecosystem: "npm" 
    directory: "/src/client-app/"  
    labels:
      - "chore"
      - "dependencies"
    commit_message:
        prefix: "⬆️ "
        include_scope: true  
    schedule:
        interval: "daily"
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/src/" # Location of package manifests
    labels:
      - "chore"
      - "dependencies"
    commit_message:
        prefix: "⬆️ " 
        include_scope: true
    schedule:
        interval: "daily"
