version: 2
updates:
  - package-ecosystem: "npm" 
    directory: "/src/client-app/"  
    schedule:
    interval: "daily"
    commit_message:
        prefix: "chore"
        include_scope: true  
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/src/" # Location of package manifests
    commit_message:
        prefix: "🧹 " 
        include_scope: true
    schedule:
        interval: "daily"
